tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      echo "Current Directory: $(pwd)"  # Check if we're in the right directory
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      if [ $? -eq 0 ]; then echo "AWS CLI Zip Downloaded Successfully"; else echo "AWS CLI Download Failed"; fi
      unzip awscliv2.zip
      if [ $? -eq 0 ]; then echo "AWS CLI Unzipped Successfully"; else echo "AWS CLI Unzip Failed"; fi
      sudo ./aws/install
      if [ $? -eq 0 ]; then echo "AWS CLI Installed Successfully"; else echo "AWS CLI Install Failed"; fi
      cd $THEIA_WORKSPACE_ROOT
  - name: react-js
    command: |
      cd frontend-react-js
      npm i
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

vscode:
  extensions:
    - 42Crunch.vscode-openapi 
    - cweijan.vscode-mysql-client2

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
